name: Publish package on github

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish on github packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@maxgfr'
          always-auth: true
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Setup .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >>  ~/.npmrc
      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
